version: "3"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres-greenlight
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
